### ISSUE TITLE
Please use generic name for data file

### ISSUE THREAD

**Issue by FanchTheSystem** [lboullu/COVIDiStress-Shiny#5]
Current data filename is COVIDiSTRESS_May_30_clean.dat :
https://github.com/lboullu/COVIDiStress-Shiny/blob/master/server.R#L9

Maybe you could use a name more generic like COVIDiSTRESS_clean.dat and use a symbolic link on your installation directory to target the good file.

On linux based os it will be something like:

```
ln -s COVIDiSTRESS_May_30_clean.dat COVIDiSTRESS_clean.dat
```

**Comment by ggautreau** [comment]
Done
